<?php
 $title = 'Dodaj z urla';
 $this->headTitle($title);
 ?>
<?php if(count($this->flashMessenger()->getMessages())) : ?>
<ul>
    <?php foreach ($this->flashMessenger()->getMessages() as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <form id="addfromurl" method="post" action="<?php echo $this->url('oferta', array('action'=>'addurl')); ?>" >
     <div class="col-lg-12">
         <div class="input-group">
             <span class="input-group-btn">
                <input type="submit" name="submit" id="wyslij" value="Dodaj z urla" class="btn btn-primary">
                <input type="text" name="url" class="form-control" id="url" autofocus="autofocus" value="<?php if(isset($url)) echo $this->escapeHtml($url); ?>">
             </span>
        </div>
     </div>
     <div class="col-md-6">
         <a href="<?php echo $this->url('oferta', array('action'=>'getlist')); ?>" class="btn btn-default" name="wroc"> Wróć</a>
     </div>
 </form>