http://dom.gratka.pl/tresc/397-48290095-pomorskie-gdansk-siedlce-malczewskiego-jacka.html<br>
http://ogloszenia.trojmiasto.pl/nieruchomosci-sprzedam/mieszkanie-gdansk-ogl8379345.html
<?php
 $title = 'Dodaj z urla';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <form id="addfromurl" method="post" action="<?php echo $this->url('oferta', array('action'=>'addurl')); ?>" >
     <div class="col-lg-12">
         <div class="input-group">
             <span class="input-group-btn">
                <input type="submit" name="submit" id="wyslij" value="Dodaj z urla" class="btn btn-primary">
                <input type="text" name="url" class="form-control" id="url" autofocus="autofocus" value="<?php if(isset($url)) echo $this->escapeHtml($url); ?>">
             </span>
        </div>
     </div>
     <div class="col-md-6">
         <a href="<?php echo $this->url('oferta', array('action'=>'getlist')); ?>" class="btn btn-default" name="wroc"> Wróć</a>
     </div>
 </form>