<?php
 $title = 'Usuń ofertę';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete the
   '<?php echo $this->escapeHtml($task->getAdres()); ?>'
 </p>
 <form action="<?php echo $this->url('oferta', array('action' => 'delete', 'id' => $id)); ?>" method="post">
 <div>
   <input type="submit" name="del" value="Yes" class="btn btn-danger" />
   <input type="submit" name="del" value="No" class="btn btn-default" />
 </div>
 </form>