<?php
 $title = 'Lista ofert';
 $this->headTitle($title);
 ?>
<?php if(count($flashMessages)) : ?>
<div class="alert alert-success fade in">
<a href="#" class="close" data-dismiss="alert">&times;</a>
<ul>
    <?php foreach ($flashMessages as $msg) : ?>
    <li> <strong>Success!</strong> <?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
</div>
<?php endif; ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
    <a href="<?php echo $this->url('oferta', array('action'=>'add'));?>" class="btn btn-primary">
        <span class="glyphicon glyphicon-list-alt"></span> Dodaj ofertę
    </a>

    <a href="<?php echo $this->url('oferta', array('action'=>'addurl'));?>" class="btn btn-primary">
        <span class="glyphicon glyphicon-list-alt"></span> Dodaj z urla
    </a>

    <a  id='dodaj-marker' class="btn btn-primary">
        <span class="glyphicon glyphicon-list-alt"></span> Dodaj marker
    </a>
</p>
 <table class="table table-striped table-bordered table-condensed table-hover" id="oferta">
 <thead>
 <tr>
     <th>Nr.</th>
     <th>Id</th>
     <th>Cena</th>
     <th>Cena/m2</th>
     <th>Liczba Pokoi</th>
     <th>Pow</th>
     <th>Dzielnica</th>
     <th>Ulica</th>
     <th>Adres</th>
     <th>Miejscowość</th>
     <th>Czynsz</th>
     <th>Rok Budowy</th>
     <th>Stan</th>
     <th>Piętro</th>
     <th>Rodzaj Budynku</th>
     <th>Ogrzewanie</th>
     <th>Opis</th>
     <th>Akcja</th>
 </tr>
 </thead>
 <tbody>
 <?php foreach ($tasks as $id => $task): ?>
 <tr>
     <td><?php echo ++$id; ?></td>
     <td><?php echo $task->getId(); ?></td>
     <td><?php echo $task->getCena(); ?></td>
     <td><?php echo $task->getCenaM2(); ?></td>
     <td><?php echo $task->getLiczbaPokoi(); ?></td>
     <td><?php echo $task->getPowierzchnia(); ?></td>
     <td><?php echo $task->getDzielnica(); ?></td>
     <td><?php echo $task->getUlica(); ?></td>
     <td><?php echo $task->getAdres(); ?></td>
     <td><?php echo $task->getMiejscowosc(); ?></td>
     <td><?php echo $task->getCzynsz(); ?></td>
     <td><?php echo $task->getRokBudowy(); ?></td>
     <td><?php echo $task->getStan(); ?></td>
     <td><?php echo $task->getPietro(); ?></td>
     <td><?php echo $task->getRodzajBudynku(); ?></td>
     <td><?php echo $task->getOgrzewanie(); ?></td>
     <td><?php // echo $task->getOpis(); ?> pokaż opis</td>
     <td>
         <a href="<?php echo $this->url('oferta',
             array('action'=>'delete', 'id' => $task->getId()));?>">Usuń</a>
         <a href="<?php echo $this->url('oferta',
             array('action'=>'edit', 'id' => $task->getId()));?>">Edytuj</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </tbody>
 </table>
<!--<div id='mapa-oferty'></div>-->
<script type="text/javascript">
    var DATA = {};
    DATA.markers_url = "<?php echo $this->serverUrl().$this->basePath('js/positions.json'); ?>";
</script>
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body…</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->