<?php
 $title = 'Dodaj nowe zadanie';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url('task', array('action' => 'add')));
 $form->get('submit')->setAttribute('value', 'Add');
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id')); 
 ?>
  <div class="col-lg-12">
    <div class="input-group">
        <span class="input-group-btn">
            <button class="btn btn-primary" type="submit">Dodaj</button>
        </span>
        <?php echo $this->formRow($form->get('title')); ?>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->
  
 <?php echo $this->form()->closeTag($form); ?>