<?php
 $title = 'Backbone ajax list';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
 <a href="<?php echo $this->url('task', array(
         'action'=>'add'));?>" class="btn btn-primary"><span class="glyphicon glyphicon-list-alt"></span> Add new</a>
</p>
<div id="task-list">
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>ID</th>
                <th>Task</th>
                <th>Akcja</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>